apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    - name: db
      port: 5432
      protocol: TCP
      targetPort: 5432
  loadBalancerIP: 192.168.56.212
  selector:
    app: postgres
