apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-persistant
  namespace: monitoring
spec:
  replicas: 1
  retention: 7d
  resources:
    requests:
      memory: 400Mi
  nodeSelector:
#    node-type: worker
     node-role.kubernetes.io/worker: "true"
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus
  tolerations:
  - key: "CriticalAddonsOnly"
  operator: "Equal"
  value: "true"
  effect: "NoExecute"
  serviceMonitorSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
#          - longhorn-prometheus-servicemonitor
          - kube-state-metrics
          - node-exporter
          - kubelet
          - traefik
  podMonitorSelector:
    matchExpressions:
      - key: name
        operator: In
        values:
          - linkerd-controller
          - linkerd-proxy
          - linkerd-service-mirror
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path  # Using K3s's default local-path provisioner
        resources:
          requests:
            storage: 20Gi