apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-chromium
  labels:
    app: selenium-node-chromium
spec:
  replicas: 2
  selector:
    matchLabels:
      app: selenium-node-chromium
  template:
    metadata:
      labels:
        app: selenium-node-chromium
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
        - name: selenium-node-chromium
          image: selenium/node-chromium
          ports:
            - containerPort: 5555
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-hub"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
          resources:
            limits:
              memory: "1000Mi"
              cpu: ".5"